<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Pingy.Core/Pingy.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="legacy-defaults.json" LogicalName="Pingy.Tests.legacy-defaults.json" />
  </ItemGroup>
</Project>
